spring:
  application:
    name: ${artifactId}
  profiles:
    active: local
swagger:
  base-package: ${basePackage}.controller
  info:
    title: ${artifactId}
server:
  error:
    include-stacktrace: always
    include-exception: true
logging:
  file: <%='${spring.application.name}.log'%>
